---
- name: Create nginx config directory
  file:
    path: "{{ nginx_config_dir }}"
    state: directory
    mode: '0755'
    recurse: yes
  tags:
  - matrix

- name: Template Nginx matrix.conf.j2
  template:
    src: matrix.conf.j2
    dest: "{{ nginx_config_dir }}/matrix.conf"
    mode: '0644'
  tags:
  - matrix
  - nginx

- name: Pull Nginx Docker image
  community.docker.docker_image:
    name: "{{ nginx_image }}"
    source: pull
  tags:
  - matrix
  - nginx

- name: Run Nginx container
  community.docker.docker_container:
    name: "{{ nginx_container_name}}"
    image: "{{ nginx_image }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ nginx_host_port }}:{{ nginx_container_port }}"
    networks:
      - name: matrix-net
      - name: patrix-net
    volumes:
      - "{{ nginx_config_dir }}/matrix.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/letsencrypt/live/{{ matrix_domain }}/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro"
      - "/etc/letsencrypt/live/{{ matrix_domain }}/privkey.pem:/etc/ssl/private/privkey.pem:ro"
  tags:
  - matrix
  - nginx