services:
  matrix-webhook:
    build: .
    restart: unless-stopped
    environment:
      - APP_PORT=3000
      - MATRIX_HOMESERVER_URL=${MATRIX_HOMESERVER_URL}
      - MATRIX_ACCESS_TOKEN=${MATRIX_ACCESS_TOKEN}
      - MATRIX_ROOM_ID=${MATRIX_ROOM_ID}
      - APP_ALERTMANAGER_SECRET=${APP_ALERTMANAGER_SECRET}
    networks:
      - matrix-net
      - patrix-net

networks:
  web-network:
    external: true
    name: matrix-net
  app-network:
    external: true
    name: patrix-net
