---
  - name: Install docker requirements
    apt:
      update_cache: yes
      name: "{{ item }}"
      state: present
    loop: "{{ requirements_packages }}"
    tags:
      - docker
      - debian
      - install
      - install-requirements

  - name: Create keyrings directory if it doesn't exist
    ansible.builtin.file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'
    tags:
      - docker
      - debian
      - install
      - keyrings

  # - name: Download docker GPG key
  #   get_url:
  #     url: "https://download.docker.com/linux/debian/gpg"
  #     dest: /etc/apt/keyrings/docker.asc
  #     mode: '0644'
  #   tags:
  #     - docker
  #     - debian  
  #     - install
  #     - gpg-key
      
  - name: Add Docker APT source.list
    copy:
      dest: /etc/apt/sources.list.d/docker.list
      content: |
        deb [arch=amd64 trusted=yes] https://nexus.mooz.jalinuxy.ir/repository/debian-docker/ bookworm main
      mode: '0644'
    notify: update apt cache
    tags:
      - docker
      - debian
      - install
      - docker-sourcelist

  - name: Install the Docker packages
    apt:
      name: "{{ item }}"
      state: present
    loop: "{{ docker_packages }}"
    tags:
      - docker
      - debian
      - install
      - docker-packages