- name: Execute only if the OS is Debian or Ubuntu
  include_tasks: docker-debian.yaml
  when: ansible_facts['os_family'] is defined and ansible_facts['os_family'] in ['Debian', 'Ubuntu']
  tags:
    - docker
    - debian
