---
- name: Create Synapse config directory
  file:
    path: "{{ synapse_config_dir }}"
    state: directory
    mode: '0755'
    recurse: yes
  tags:
  - matrix
  - synapse

- name: Create Synapse data directory
  file:
    path: "{{ synapse_data_dir }}"
    state: directory
    mode: '0755'
    recurse: yes
  tags:
  - matrix
  - synapse

- name: Template homeserver.yaml
  template:
    src: homeserver.yaml.j2
    dest: "{{ synapse_data_dir }}/homeserver.yaml"
    mode: '0644'
  tags:
  - matrix
  - synapse

- name: Pull Synapse Docker image
  community.docker.docker_image:
    name: "{{ synapse_image }}"
    source: pull
  tags:
  - matrix
  - synapse

- name: Run Synapse container
  community.docker.docker_container:
    name: "{{ synapse_container_name }}"
    image: "{{ synapse_image }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: patrix-net
    volumes:
      - "{{ synapse_config_dir }}:/config:rw"
      - "{{ synapse_data_dir }}:/data:rw"
  tags:
  - matrix
  - synapse