---
- name: Create Coturn config directory
  file:
    path: "{{ coturn_config_dir }}"
    state: directory
    mode: '0755'
    recurse: yes
  tags:
    - matrix
    - coturn

- name: Template Coturn coturn.conf
  template:
    src: coturn.conf.j2
    dest: "{{ coturn_config_dir }}/{{ coturn_config_file }}"
    mode: '0644'
  tags:
    - matrix
    - coturn

- name: Pull Coturn Docker image
  community.docker.docker_image:
    name: "{{ coturn_image }}"
    source: pull
  tags:
    - matrix
    - coturn

- name: Run Coturn container
  community.docker.docker_container:
    name: "{{ coturn_container_name }}"
    image: "{{ coturn_image }}"
    state: started
    restart_policy: unless-stopped
    networks:
      - name: patrix-net
    volumes:
      - "{{ coturn_config_dir }}/{{ coturn_config_file }}:/etc/coturn/turnserver.conf:ro"
    command: ["-c", "/etc/coturn/turnserver.conf"]
  tags:
    - matrix
    - coturn